### ISSUE TITLE
Eclipse not recognizing library "CoreLibrary"

### ISSUE THREAD

**Issue by TonserTorben** [xatkit-bot-platform/xatkit-releases#11]
Hi 
I've followed the guide on how to install this framework. 
However, when I open eclipse to make changes to E.g. GreetingsBot, the editor can't resolve the library "CoreLibrary". 

I've read somewhere that the corelibrary is now standalone. 
But how do I set this up?

Thanks in advance

**Comment by TonserTorben** [comment]
FYI. The same is the case for the platform "ChatPlatform"

**Comment by TonserTorben** [comment]
![image](https://user-images.githubusercontent.com/9077986/66907566-d32fae00-f009-11e9-8aa1-f0983f774d4a.png)

**Comment by gdaniel** [comment]
Hi,

Thanks for reporting this issue, which version of Xatkit are you using, and which version of the eclipse plugins?

The latest versions are:
- xatkit 3.0.0
- xatkit-eclipse 2.1.0

If you have the latest version I'll need some additional information regarding your setup:
- what is your operating system? 
- Is there anything particular in your $XATKIT path (spaces, accents, special chars)
- Are you using the release version of Xatkit or the XDK?

**Comment by TonserTorben** [comment]
I downloaded yesterday, so it's xatkit 3.0.0 and xatkit-eclipse 2.1.0. 
I followed the instructions on the wiki https://github.com/xatkit-bot-platform/xatkit-releases/wiki/Installation

I'm running windows 10.
The path only contains normal chars and dashes.
I've tried both but with the same result.

**Comment by gdaniel** [comment]
Ok, I'll try to reproduce this.
Did you install the update site using the zip or the URL? I just saw that the URL in the release notes is incorrect, the right one is https://xatkit-bot-platform.github.io/xatkit-runtime-docs/releases/v2.1.0/update/

**Comment by TonserTorben** [comment]
I used the zip file. 
However I've managed to solve part of the problem. 
It seems that maven wasn't set up correctly for me. (Didn't know that was a requirement)
After setting up Maven correctly. The CoreLibrary doesn't give an error anymore. 

But it seems like the build.sh has trouble building the platforms. 

![image](https://user-images.githubusercontent.com/9077986/66911394-b5197c00-f010-11e9-9f36-7da7b730c0fe.png)

Any idea what I'm doing wrong?

**Comment by gdaniel** [comment]
Can you send me the full build log? It seems that something wrong happened before.

Maven is only required when using the XDK https://github.com/xatkit-bot-platform/xatkit-dev

**Comment by TonserTorben** [comment]
[Build Output.txt](https://github.com/xatkit-bot-platform/xatkit-releases/files/3733819/Build.Output.txt)

This is the full build output. I've altered the mvn_options in build.sh to "-e" to get more info about the errors.

**Comment by gdaniel** [comment]
I tried to reproduce your issue locally but everything seems to work for me when I install Xatkit from the release page.

I'd suggest the following steps:

- delete all you xatkit-related directories, and also delete `XATKIT*` environment variables.
- uninstall xatkit from eclipse
- download `xatkit_3.0.0.zip` and `xatkit-update-site_2.1.0.zip` from the release page
- unzip `xatkit_3.0.0.zip`, and run `xatkit-install-windows.bat` with administrative rights, then check that the `XATKIT` environment variable points to your xatkit directory
- (re)start eclipse (this is required to update the environment variables) and install the update-site
- open the greetings bot, and tell me if you still have the issue

You don't need maven to use Xatkit, it is only required to compile it with the XDK. The errors I see from your log looks like a Java version issue, Xatkit doesn't work for versions above [see this issue](https://github.com/xatkit-bot-platform/xatkit-releases/issues/6).

**Comment by TonserTorben** [comment]
Thanks, somehow that worked.

**Comment by gdaniel** [comment]
Good, I suspect it was an environment variable issue. The eclipse error should be more explicit about the path actually used to load the libraries/platforms, I'll open it.
